name: Example action
description: A simple example of a composite action with an input

inputs:
  my-awesome-input:
    description: My awesome input
    required: true

runs:
  using: composite
  steps:
    - name: Print some text
      if: ${{ !(inputs.my-awesome-input == 'true') }}
      run: echo "Wow"
      shell: bash
