# .github/workflows/docker.yml
name: Build and push Docker Image

env:
  OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: actions-example-image

on:
  schedule:
    # Weekly, at 03:00 on Monday UTC time
    - cron: "0 3 * * 1"
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      - "docker-build-example/image/**"
      - "!docker-build-example/image/README.md"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "docker-build-example/image/**"
      - "!docker-build-example/image/README.md"
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v4
      
      - name: Build image 🛠
        run: docker build --rm --force-rm --tag ${{ env.OWNER }}/${{ env.IMAGE_NAME }} docker-build-example/image/

      - name: Login to Docker Hub 🔐
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image 📤
        run: docker push --all-tags ${{ env.OWNER }}/${{ env.IMAGE_NAME }}
