name: Example to pass output from one job to another

on:
  pull_request:
    paths:
      - ".github/workflows/pass-output.yml"
  push:
    branches:
      - main
    paths:
        - ".github/workflows/pass-output.yml"
  workflow_dispatch:

jobs:
  produce-output:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      my-important-output: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"

  consume-output:
    runs-on: ubuntu-latest
    needs: produce-output
    steps:
      - env:
          MY_OUTPUT: ${{needs.produce-output.outputs.my-important-output}}
        run: echo "$MY_OUTPUT"
