name: Example to pass a file from one job to another

on:
  pull_request:
    paths:
      - ".github/workflows/pass-file.yml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/pass-file.yml"
  workflow_dispatch:

jobs:
  upload-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file 💾
        run: echo "some-crazy-file" > awesome-file.txt

      - name: Upload tags file 💾
        uses: actions/upload-artifact@v4
        with:
          name: awesome-artifact
          path: awesome-file.txt
          retention-days: 3

  download-job:
    runs-on: ubuntu-latest
    needs: upload-job
    steps:
      - name: Download artifact 📥
        uses: actions/download-artifact@v6
        with:
          name: awesome-artifact
          path: /tmp

      - name: Cat file ✅
        run: cat /tmp/awesome-file.txt
