name: Example to run a strategy

on:
  pull_request:
    paths:
      - ".github/workflows/strategy.yml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/strategy.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        os: [macos-latest, windows-latest, ubuntu-22.04]

        include:
          - node-version: 20.x
            os: macos-latest

        exclude:
          - node-version: 18.x
            os: ubuntu-22.04

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
